modLoader = "javafml"
issueTrackerURL = "https://github.com/kawaiicakes/VassalCore/issues"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "vassalcore"
version = "${mod_version}"
displayName = "Vassal Core"
authors = "${mod_authors}"
description = "${mod_description}"

[[dependencies.vassalcore]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.vassalcore]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"